name: Build container

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker login -u coderookieerick -p ${{ secrets.BUREAUCRAT_TOKEN }}
          docker build -t bureaucrat .
          docker tag bureaucrat coderookieerick/bureaucrat
          docker push coderookieerick/bureaucrat:latest