name: Publish container

on:
  push:
    branches: [ "publish" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        run: |
          cd frontend
          npm i
          npm run build
          cd ..
          docker build -t bureaucrat .
          docker stop bureaucrat_test || true
          docker run -d --rm --name bureaucrat_test -p 19760:19760 bureaucrat
          python3 -m venv testenv
          source testenv/bin/activate
          pip install requests
          pip install pytest
          pytest
          deactivate

      - name: Cleanup
        if: always()
        run: |
          docker stop bureaucrat_test || true

      - name: Publish container
        run: |
          docker login -u coderookieerick -p ${{ secrets.BUREAUCRAT_TOKEN }}
          docker tag bureaucrat coderookieerick/bureaucrat
          docker push coderookieerick/bureaucrat:latest