name: Local auto publish (1am or push)

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-test
    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Ensure local startup
        run: |
          docker stop bureaucrat_test || true
          docker build -t bureaucrat_local --build-arg BUREAUCRAT_API_HOST=https://test.moradev.dev/apps/bureaucrat --build-arg BUREAUCRAT_SITE_BASENAME=/apps/bureaucrat .
          docker stop bureaucrat_local || true
          docker rm bureaucrat_local || true
          docker run -d --name bureaucrat_local -p 19970:19970 bureaucrat_local