name: Scheduled publish container

on:
  schedule:
    - cron: "* 4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      
      - uses: actions/checkout@v3

      - name: Build
        run: |
          cd frontend
          npm i
          npm run build
          cd ..
          docker build -t bureaucrat --no-cache .
      
      - name: Test
        run: |
          docker stop bureaucrat_test || true
          docker run -d --rm --name bureaucrat_test -p 19760:19760 bureaucrat
          python3 -m venv testenv
          source testenv/bin/activate
          pip install requests
          pip install pytest
          pytest

      - name: Cleanup
        if: always()
        run: |
          docker stop bureaucrat_test || true
          deactivate