name: Publish Nuget Library

on:
  push:
    branches: [ "nuget" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test library
        run: |
          cd net
          VERSION="gha+"$(date "+%s")
          dotnet test Bureaucrat.Test
          dotnet pack Core/Bureaucrat.Core.csproj --version-suffix $VERSION -o ./package
          dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json