name: Publish python client

on:
  push:
    branches: [ "python-client" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and publish
        run: |
          cd lib
          python3 -m venv publishdev
          source publishdev/bin/activate
          pip install build
          pip install setuptools
          pip install twine
          python3 -m build
          twine upload -u __token__ -p ${{ secrets.PYBUREAUCRAT_TWINE_TOKEN }} dist/*
          deactivate