name: Publish Nuget package

on:
  push:
    branches: [ "nuget" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test
        run: |
          dotnet test ./net/Bureaucrat.Test

      - name: Pack
        run: |
          dotnet pack ./net/Core/Bureaucrat.Core.csproj --version-suffix $VERSION -o ./package

      - name: Publish package to nuget
        run: |
          dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json