name: Publish python client

on:
  push:
    branches: [ "python-client" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: dockerable
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and run container
        run: |
          docker build -t bureaucrat .
          docker stop bureaucrat_test || true
          docker run -d --rm --name bureaucrat_test -p 19970:19970 bureaucrat

      - name: Test
        working-directory: ./lib
        run: |
          python3 -m venv testenv
          pip install pytest 
          pip install requests
          pytest

      - name: Stop container
        if: always()
        run: |
          docker stop bureaucrat_test || true

      - name: Build package
        working-directory: ./lib
        run: |
          python3 -m venv buildenv
          source buildenv/bin/activate
          pip install build
          pip install setuptools
          python3 -m build
          deactivate

      - name: Publish package
        working-directory: ./lib
        run: |
          python3 -m venv publishenv
          source publishenv/bin/activate
          pip install twine
          twine upload -u __token__ -p ${{ secrets.PYBUREAUCRAT_TWINE_TOKEN }} dist/*
          deactivate
