name: Nuget

on:
  push:
    branches: [ "nuget" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Test container with Net project
        run: |
          docker build -t bureaucrat .
          docker run -d --rm --name bureaucrat_test -p 19971:19970 bureaucrat
          dotnet test ./net/Bureaucrat.Test/Bureaucrat.Test.csproj

      - name: Stop container
        if: always()
        run: |
          docker stop bureaucrat_test || true

  build:
    needs: [ test ]
    runs-on: dockerable
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pack
        run: |
          dotnet pack ./net/Core/Bureaucrat.Core.csproj -o ./package

      - name: Publish package to nuget
        run: |
          dotnet nuget push ./package/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json