name: Publish site

on:
  push:
    branches: [ "documentation-site" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish site
        run: |
          python3 -m venv testenv
          source testenv/bin/activate
          pip install jinja2
          python3 build_templates.py
          rm -r /var/www/php/bureaucrat/* || true
          cp -r site/* /var/www/php/bureaucrat