name: Build container

on:
  push:
    branches: [ "site" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-01
    steps:
      - uses: actions/checkout@v3

      - name: Publish site locally
        run: |
          rm -r /var/www/php/bureaucrat/* || true
          cp -r site/* /var/www/php/bureaucrat