name: Test python client
run-name: Python client scheduled test
on:
  schedule:
    - cron: "50 3 * * *"
    - cron: "50 17 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Test container with python client
        working-directory: ./lib
        run: |
          docker build -t bureaucrat ..
          docker run -d --rm --name bureaucrat_test -p 19971:19970 bureaucrat
          python3 -m venv testenv
          source testenv/bin/activate
          pip install pytest pytest-asyncio requests
          pytest
          deactivate

      - name: Stop container
        if: always()
        run: |
          docker stop bureaucrat_test || true